### PR TITLE
Clickable org-roam-graph

### PR DESCRIPTION
**Pull request by jethrokuan**
SVG makes the graph nodes clickable:

https://drive.google.com/file/d/1TqZyD98wSRkZ_h5uSVJvRXOuAW4-VofB/view?usp=sharing

Setup for this is a bit more involved (using a custom protocol, registering it in linux etc.). I like it and will likely keep it in. Shouldn't affect other users (just unclickable).

# Todo
- [x] Remove hard-coded image viewer (now firefox)
- [x] Check for graphviz before use

# Future plans
Move to an interactive d3 html page with clickable roam links.

### CODE REVIEW

**Comment by jethrokuan** [comment]
## Setup Instructions

Create in `~/.local/share/applications/roam.desktop`:

```
[Desktop Entry]
Name=Emacs Client
Exec=/home/jethro/.local/bin/launch_emacs %u
Icon=emacs-icon
Type=Application
Terminal=false
MimeType=x-scheme-handler/roam
```

**Comment by yohfdo** [comment]
> ## Setup Instructions
> 
> Create in `~/.local/share/applications/roam.desktop`:
> 
> ```
> [Desktop Entry]
> Name=Emacs Client
> Exec=/home/jethro/.local/bin/launch_emacs %u
> Icon=emacs-icon
> Type=Application
> Terminal=false
> MimeType=x-scheme-handler/roam
> ```
> 
> Create `$HOME/.local/bin/launch_emacs`:
> 
> ```
> #!/usr/bin/env bash
> emacsclient "${1#*:}"
> ```
> 
> `xdg-mime default roam.desktop x-scheme-handler/roam`

On Kubuntu 18.04, Emacs 28.0.50, Firefox

Emacs noob here, but this method doesn't seem to work for me to click the link and open in Emacs. Just get an error from Firefox that it doesn't know what to do with `roam://`.  I had to follow some of the instructions here: https://github.com/alphapapa/org-protocol-capture-html#org-protocol-instructions

What I did different to the instructions [above](https://github.com/jethrokuan/org-roam/pull/12#issuecomment-581891278):

Changed the last `Exec`, `Categories` and `MimeType` lines of `~/.local/share/applications/roam.desktop` to:

```
Emacs=emacsclient %u
Categories=System;
MimeType=x-scheme-handler/org-roam;
```

Then run `kbuildsycoca4`

Add `(server-start)` to `init.el`. 

Also added the additional Firefox configuration listed here: https://github.com/alphapapa/org-protocol-capture-html#3-configure-firefox

Now when I click a node in the graph, Emacs opens, but its a blank buffer with the file name `filename.rg<roam:>`. For example, if I opened the file `setup_org_roam.org`, the buffer/filename is `setup_org_rom.org<roam:>`

**Comment by igoralmeida** [comment]
@yohfdo note how `launch_emacs` in the example calls `emacsclient ${1#*:}`, which is bash's "remove matching prefix pattern". I understand this to turn `roam:///path/to/orgroam/file.org` into `///path/to/orgroam/file.org`.

I don't think you can do that kind of magic inside `roam.desktop`.

**Comment by yohfdo** [comment]
I finally got it to work. As @igoralmeida mentioned, I had to include `emacsclient ${1#*:}`in the `launch_emacs` file and commented out `(server_start)` in the `init.el` file. So now my `roam.desktop` file looks like:

```
[Desktop Entry]
Name=Org-Roam Client
Exec=/home/yohan/.local/bin/launch_emacs %u
Icon=emacs-icon
Type=Application
Terminal=false
Categories=System;
MimeType=x-scheme-handler/roam;
```

**Pull request merged**
