### PR TITLE
Add Spacemacs installation instructions

### PR DESCRIPTION
**Pull request by hendrikcech**
As requested in issue #24, I added some instructions on how to install org-roam as a Spacemacs user.

### CODE REVIEW

**Comment by honza** [comment]
This doesn't actually work for me. The menu item (`ar`) isn't added, and I can't access the `org-roam-*` functions from `M-x`. Is there a step missing?

**Comment by hendrikcech** [comment]
No, I don't think so, it works for me. Did you add `org-roam` to your `.spacemacs` configuration file and did you restart emacs afterwards?

**Comment by honza** [comment]
> Did you add org-roam to your .spacemacs configuration file and did you restart emacs afterwards?

Yep!

**Comment by honza** [comment]
I just figured it out. The `after org` directive. You need to open a random org file at least once, and then it works. Thanks

**Comment by CeleritasCelery** [comment]
Why not just add this to Spacemacs directly instead of putting the code in a readme here?

**Comment by jethrokuan** [comment]
> Why not just add this to Spacemacs directly instead of putting the code in a readme here?

I think it's fine to have the installation instructions here too. Especially since it's still subject to some change.

**Comment by aneeshsathe** [comment]
I'm getting an error as in the image below. Though i can see org-roam as a menu item, I can't open anything and I get a 'wrong type argument: commandp, org-roam-findfile' error.

This is even after opening a random org file as @honza suggested. 

Thank you for the directions @hendrikcech !
Annotation 2020-02-20 195552

**Comment by jethrokuan** [comment]
> 'wrong type argument: commandp, org-roam-findfile

did you type this? I can't find an instance of `org-roam-findfile`.

Not sure about the quelpa error though, probably best to clear the cache and redownload.

**Comment by aneeshsathe** [comment]
yes i typed it, sorry for the confusing typo

i get the same error for whatever org-roam-XYZ function i try

I will try to clear cache. if it helps to understand it's a fresh emacs+spacemacs install on windows. 
- any possibility that I might not have a very commonly used package which might not be mentioned?

**Comment by aneeshsathe** [comment]
after deleting the contents of '...emacs.d/.cache/' and restarting emacs I got the error below during install:
image

**Comment by jethrokuan** [comment]
Seems like a quelpa thing again: https://github.com/syl20bnr/spacemacs/issues/8901

**Comment by aneeshsathe** [comment]
Hello, I think the quelpa access to tar.exe issue might be fixed... but it's still not working now I'm seeing the following in the Messages buffer: 

```
Updating c:/Users/anees/.emacs.d/.cache/quelpa/build/org-roam/

c:/Users/user/.emacs.d/.cache/quelpa/build/org-roam/org-roam-utils.el -> c:/Users/anees/AppData/Local/Temp/org-roam97kvgR/org-roam-20200221.1545/org-roam-utils.el

c:/Users/user/.emacs.d/.cache/quelpa/build/org-roam/org-roam.el -> c:/Users/anees/AppData/Local/Temp/org-roam97kvgR/org-roam-20200221.1545/org-roam.el

Wrote c:/Users/user/.emacs.d/.cache/quelpa/packages/org-roam-readme.txt

Error getting PACKAGE-DESC: (file-missing Opening input file No such file or directory c:/Users/user/.emacs.d/.cache/quelpa/packages/org-roam-20200221.1545.tar)
```

And this in the package-build-checkout:

```
Fetching origin
HEAD is now at d02d48e (bugfix): prevent multiple async build processes (#149)
'tar.exe: Failed to open '/c/Users/anees/.emacs.d/.cache/quelpa/packages/org-roam-20200221.1545.tar'
2020-02-21 15:45:54 +0800'
```
I'm a little confused by the `/c/Users/...` when I think it should be `c:/Users/...` ?

Thank you again for all your help!

**Comment by zou000** [comment]
I met the same commandp error:
Screen Shot 2020-02-21 at 11 09 18 PM

**Comment by mchowning** [comment]
> Found a way to fix it: delete the ~/.emacs.d/elpa/org-roam-* directory and restart emacs.

I had the commandp error too, but this fixed it for me. Thanks @zou000 !

**Comment by urbanslug** [comment]
It seems I have the same problem as @aneeshsathe, the current spacemacs instructions don't work for me either. What could I be doing wrong?


**Environment**
 - Spacemacs
 - MacOS Catalina 10.15.3 

----
**Errors**
1. I get the error below when I start emacs:
```
 An error occurred while installing org-roam (error: (wrong-type-argument package-desc nil))
```

2. Attempting to use org-roam find-file gives me
```
command-execute: Wrong type argument: commandp, org-roam-find-file
```
----

**Attempts at debugging**
 1. Removing `elpa/org-roam-*`

I don't have any `elpa/org-roam-*` directory. What I have is:
```
find ~/.emacs.d -d -name 'org-roam-*'
/Users/me/.emacs.d/.cache/quelpa/packages/org-roam-readme.txt
/Users/me/.emacs.d/.cache/quelpa/packages/org-roam-20200224.1358.tar
/Users/me/.emacs.d/.cache/quelpa/build/org-roam/doc/images/org-roam-buffer.gif
/Users/me/.emacs.d/.cache/quelpa/build/org-roam/doc/images/org-roam-intro.png
/Users/me/.emacs.d/.cache/quelpa/build/org-roam/doc/images/org-roam-graph.gif
/Users/me/.emacs.d/.cache/quelpa/build/org-roam/doc/images/org-roam-insert-filetag.gif
/Users/me/.emacs.d/.cache/quelpa/build/org-roam/doc/images/org-roam-find-file.gif
/Users/me/.emacs.d/.cache/quelpa/build/org-roam/org-roam-utils.el
```

Deleting org-roam files with `find ~/.emacs.d -d -name 'org-roam-*' -delete` and restarting emacs didn't fix it.

2. Cloning org-roam by hand

I had to clone the repo myself because emacs just couldn't fetch it.
```
git clone https://github.com/jethrokuan/org-roam/ ~/.emacs.d/elisp/org-roam
```

3. I also tried this solution from reddit https://www.reddit.com/r/spacemacs/comments/f6epwo/total_noob_how_do_i_install_orgroam_in_spacemacs/
 ---
**Config**

My `~/.emacs.d/private/org-roam/packages.el` is the same as the on in the spacemacs installation instructions
```elisp
(defconst org-roam-packages
  '((org-roam :location
        (recipe :fetcher github :repo "jethrokuan/org-roam" :branch "develop"))))

(defun org-roam/init-org-roam ()
    (use-package org-roam
        :after org
        :hook
        (after-init . org-roam-mode)
        :custom
        (org-roam-directory "/Users/me/src/org/roam-notes")
        :init
        (progn
          (spacemacs/declare-prefix "ar" "org-roam")
          (spacemacs/set-leader-keys
            "arl" 'org-roam
            "art" 'org-roam-today
            "arf" 'org-roam-find-file
            "arg" 'org-roam-show-graph)

          (spacemacs/declare-prefix-for-mode 'org-mode "mr" "org-roam")
          (spacemacs/set-leader-keys-for-major-mode 'org-mode
            "rl" 'org-roam
            "rt" 'org-roam-today
            "rb" 'org-roam-switch-to-buffer
            "rf" 'org-roam-find-file
            "ri" 'org-roam-insert
            "rg" 'org-roam-show-graph))))

```

**Comment by igoralmeida** [comment]
This is not an *elpa problem. Apparently, `org-roam-find-file` (and friends) only works if `org-roam-mode` has been called, AND the example private layer says explicitly `:after org`.

Just after starting spacemacs (develop), I need to open something in org-mode (like the agenda, `SPC a o a`) before I'm able to see the org-roam menu in `SPC a r`.
THEN, I need to call `org-roam-mode` before `SPC a r f` (`org-roam-find-file`), otherwise I get the `commandp` error.

I don't understand why that `(after-init . org-roam-mode)` line is not working...

**Comment by komali2** [comment]
> This is not an *elpa problem. Apparently, `org-roam-find-file` (and friends) only works if `org-roam-mode` has been called, AND the example private layer says explicitly `:after org`.
> 
> Just after starting spacemacs (develop), I need to open something in org-mode (like the agenda, `SPC a o a`) before I'm able to see the org-roam menu in `SPC a r`.
> THEN, I need to call `org-roam-mode` before `SPC a r f` (`org-roam-find-file`), otherwise I get the `commandp` error.
> 
> I don't understand why that `(after-init . org-roam-mode)` line is not working...

This works for me as a temporary solution. Thanks for the discovery!

**Comment by jethrokuan** [comment]
> I don't understand why that (after-init . org-roam-mode) line is not working...

how are you launching Emacs? Also, the bindings should really be on `org-roam-mode` and not `org-mode`.

**Pull request merged**
