### PR TITLE
(feat) Added neato support

### PR DESCRIPTION
**Pull request by andresm**
neato is able to create more compact graphs than dot. It reduces the horizontal scrolling when navigating big graphs.

### CODE REVIEW

**Comment by alanz** [comment]
I have not run this, so have no idea what it looks like.  But a more vertical layout might make sense, as shown in https://dev2.wiki.innovateoregon.org/view/welcome-visitors/view/preview-next-diagram

The relevant bit is something like 
```
DOT strict digraph

rankdir=LR

  node [style=filled fillcolor=lightyellow penwidth=5 color=black fontname=\"Helvetica-bold\"]
  HERE NODE

    node [style=filled fillcolor=lightblue]
    WHERE /^Next/
      LINKS HERE -> NODE
          node [style=filled fillcolor=white]
          HERE NODE
            WHERE /^Next/
              LINKS HERE -> NODE

    node [style=filled fillcolor=white penwidth=3 color=black fontname=\"Helvetica\"]
    LINKS HERE -> NODE
       node [style=filled fillcolor=white penwidth=1 color=black fontname=\"Helvetica\"]
       HERE NODE
         LINKS HERE -> NODE
```
Note: this is a fedwiki template, from viewing the JSON of the diagram, in the footer.

**Comment by bdarcus** [comment]
> I have not run this, so have no idea what it looks like. But a more vertical layout might make sense, as shown in https://dev2.wiki.innovateoregon.org/view/welcome-visitors/view/preview-next-diagram

That's a pretty awesome UI! Would be cool to see something like that in org-roam export.

**Comment by jethrokuan** [comment]
Rather than add another customization option, couldn't this be achieved by setting the graphviz executable directly to neato?

```
(setq org-roam-graphviz-executable (executable-find "neato"))
```

I don't mind adding `overlap=false;` into the graph.

**Comment by alanz** [comment]
Perhaps we should consider `rankdir=LR`?
http://martin-loetzsch.de/S-DOT/rankdir.html
This makes the long dimension vertical, like a normal web page, and does not penalize nodes with long names.

**Comment by jethrokuan** [comment]
I'll add a variable that will allow adding extra options. E.g. 

```
(setq org-roam-graph-extra-options '(("rankdir" . "LR")))
```

I gave that option a try, and found that the average distance between nodes went up significantly.

Tbh graphviz at this point is a stopgap solution. I'm hoping to eventually move to something more sophisticated like d3.

- keyboard navigation of nodes
- hide/show arbitrarily deep layers
- proper force-based layout

Unfortunately my web skills are not that great 😬

**Comment by andresm** [comment]
Here are examples of a graph generated by dot and neato:

[GraphViz dot file. Node as Chess order](https://stackoverflow.com/questions/20473268/graphviz-dot-file-node-as-chess-order)

Regarding the extra options: I kept both paths in the code to be able to switch between dot and neato easily, and allow the user to configure both paths in case the automatic identification fails.

**Comment by jethrokuan** [comment]
> allow the user to configure both paths in case the automatic identification fails.

I think users can be expected to configure the path to the executable used appropriately themselves, the extra search for the dot executable can actually be removed

**Pull request closed without merging**
