### PR TITLE
Update org-roam-graph variable names

### PR DESCRIPTION
**Pull request by progfolio**
###### Motivation for this change
See: https://github.com/jethrokuan/org-roam/issues/382

### CODE REVIEW

**Comment by jethrokuan** [comment]
is there a reason why `org-roam-grapher-extra-options` is does not have the `org-roam-graph` prefix?

**Comment by progfolio** [comment]
> is there a reason why org-roam-grapher-extra-options does not have the org-roam-graph prefix?

It probably slipped through the linting because it matches the regexp `^org-roam-graph.*`
looks like `makem.sh` is using `package-lint` which checks with the following:

```emacs-lisp
(defun package-lint--get-package-prefix ()
  "Return package prefix string (i.e. the symbol the package `provide's).
Prefix is returned without any `-mode' suffix."
  (let ((feature (package-lint--provided-feature)))
    (when feature
      (replace-regexp-in-string "-mode\\'" "" feature))))
```

I agree it's not a very good name. How about changing it to something like `org-roam-graph-executable-options`? Or any other suggestions?

**Comment by jethrokuan** [comment]
These options are not for the graphviz executable, but injected into the graphviz output to configure the graph output. Maybe `org-roam-graph-extra-config` or something? And alias the past 2 names.

**Comment by progfolio** [comment]
Ah, understood. Declaring the aliased versions obsolete as well?

**Comment by jethrokuan** [comment]
> Ah, understood. Declaring the aliased versions obsolete as well?

Sure!

**Pull request merged**
