### PR TITLE
Add graph rendering

### PR DESCRIPTION
**Pull request by jethrokuan**
So now I have 2 graph modes:

1. Ascii with graph-easy:

image

2. Graphviz

image

The ascii mode is a mess, but can possibly become interactive. The graphviz mode gives a nice overview, but is not interactive.

I think eventually what I'll do is create the n-degree graph: show all nodes at most n degrees away, and their edges, this should provide a good compromise for the ascii version.

### CODE REVIEW

**Comment by jethrokuan** [comment]
See #2

**Comment by l3kn** [comment]
Regarding limiting the depth of the graph,
I wrote some code for it at https://github.com/l3kn/org-zettelkasten/blob/master/org-zk-graphviz.el

One idea I had for making it interactive was adding a 2/3 character https://github.com/abo-abo/avy style hint to each node.

**Comment by jethrokuan** [comment]
Looks like Emacs can render SVG, which can contain hyperlinks. I think I'll merge this in first, and work on the SVG one later. The avy style hints should be achievable via some external package that deals with links i.e. I don't have to write them.

**Comment by alphapapa** [comment]
> Looks like Emacs can render SVG, which can contain hyperlinks. I think I'll merge this in first, and work on the SVG one later. The avy style hints should be achievable via some external package that deals with links i.e. I don't have to write them.

Can you please point me to more info about that?  I'm very interested, e.g. https://github.com/alphapapa/org-graph-view

**Comment by jethrokuan** [comment]
> Can you please point me to more info about that? 
https://www.gnu.org/software/emacs/manual/html_node/elisp/SVG-Images.html

Check this out :D I really like the clickable svgs, I think it makes the graph infinitely more useful. i'm going to move away from graphviz to some nice d3 probably. Unfortunately resizing and such is still painfully slow, so I'm avoiding the display in Emacs.



> Also, where is the code for the "graph-easy" ASCII graph? I can't find that in org-roam.el.

Not committed in. It's just replacing `dot` with `graph-easy`, which is [a perl thing](https://metacpan.org/pod/Graph::Easy).

**Comment by alphapapa** [comment]
I have something pretty exciting to show regarding SVG and Org graphs in Emacs.  Stay tuned...

**Comment by alphapapa** [comment]
I have interactivity working!  You can click with mouse-1 to recenter the graph on a node and show the entry in the Org buffer, mouse-2 to zoom in on it (and narrow the corresponding Org buffer) to that tree, and mouse-3 to zoom out one level from a node (and in the Org buffer).  I hooked the Emacs theme colors into graphviz, so it looks like it's just part of Emacs.  doom-themes look amazing with it.
output-2020-02-04-12:01:26

**Comment by alphapapa** [comment]
output-2020-02-04-12:09:10

**Comment by jethrokuan** [comment]
Very nice! Are the nodes in the image clickable? Is this something I can pull in to try with my own cache data?

**Comment by alphapapa** [comment]
Yes, the nodes in the image are clickable.  You can zoom in and out and recenter the graph by clicking them.

The graph is built from `org-element-parse-buffer`.  You can see all the code here: https://github.com/alphapapa/org-graph-view/tree/wip/dot

**Comment by xianwenchen** [comment]
> Check this out :D I really like the clickable svgs, I think it makes the graph infinitely more useful. i'm going to move away from graphviz to some nice d3 probably. Unfortunately resizing and such is still painfully slow, so I'm avoiding the display in Emacs.

Resizing graph generated from org-roam-graph-show is still slow.

I see that pull request #7 was merged. Is there some way to use the graph tool suggested by alphapapa in org-roam now?

**Pull request merged**
