### PR TITLE
(ehancement): Improve org-roam-graph

### PR DESCRIPTION
**Pull request by progfolio**
Allow showing/building the whole graph from any buffer.
Allow programatically specifying connected component path.

### CODE REVIEW

**Comment by progfolio** [comment]
Simple enough change, and everything seems to work fine on my end. Appreciate it if anyone can give it a try before we push.

**Comment by zaeph** [comment]
It works on my end.

**Comment by zaeph** [comment]
I'm wondering if we could change the `buffer-file-name` to also include indirect buffers.

**Comment by zaeph** [comment]
> I'm wondering if we could change the `buffer-file-name` to also include indirect buffers.

Done in e6ee56549ca71d62b2bf8a676f6dfcedb6b09f99.  What do you think?

**Comment by zaeph** [comment]
Whoops, good catch on f8dbdc97c1b4d7b943a539e1bd5cbb589458998b.

Ready to merge?

**Comment by progfolio** [comment]
Sorry! Was working on it at the same time. I think we can just pass the result of `(base-buffer-name)` as the arg to `buffer-file-name`. If it is nil, the current buffer will still be used. Sound good?

**Comment by zaeph** [comment]
> Sorry! Was working on it at the same time. I think we can just pass the result of `(base-buffer-name)` as the arg to `buffer-file-name`. If it is nil, the current buffer will still be used. Sound good?

Yup, that sounds good to me.  Merge?

**Pull request merged**
